### ISSUE TITLE
Question about clone_many_times()

### ISSUE THREAD

**Issue by lisabug** [oxford-cs-ml-2015/practical6#5]
I'm curious about why should we unroll the LSTM to _T_ timesteps. Since all copies share the same parameters, every time doing bp step makes the LSTM's parameters and gradPrameters changing. Why do we just use one LSTM make fp repeatedly from t = 1 to _T_ and then bp from t = _T_ to 1 repeatedly.
Because I wanted imply LSTM as a decoder to generate sentence, I have to handle the sequence of variant length. However, I tried my thought but failed.
Could someone help me, thanks honestly.

**Comment by bshillingford** [comment]
You need clones to store intermediate activations. These are needed for
correctly computing gradients.

**Comment by lisabug** [comment]
I got it, thanks for your help:)
